### ISSUE TITLE
Issues with the code

### ISSUE THREAD

**Issue by brunodom** [ihewitt/VO2max#3]
Hi @ihewitt , I am trying to follow your instruction and I am using Arduino IDE 2.2.1 on Win11. I have installed the ESP32 Dev Module and using the parameters in your source code. However, I am getting these errors on the compilation:

In file included from C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:37:
c:\Users\bruno\OneDrive\Documents\Arduino\libraries\TFT_eSPI/TFT_eSPI.h:973:8: warning: #warning >>>>------>> TOUCH_CS pin not defined, TFT_eSPI touch functions will not be available! [-Wcpp]
       #warning >>>>------>> TOUCH_CS pin not defined, TFT_eSPI touch functions will not be available!
        ^~~~~~~
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
                         {icount++, "Done.", false, 0, 0}};
                                                         ^
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino: In function 'void doMenu()':
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:1020:18: error: variable 'sel' set but not used [-Werror=unused-but-set-variable]
             bool sel;
                  ^~~
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:1048:23: error: format '%d' expects argument of type 'int', but argument 5 has type 'void (*)()' [-Werror=format=]
         Serial.printf("cur %d, %d, %d", cur, menuitems[cur].toggle, menuitems[cur].fn);
                       ^~~~~~~~~~~~~~~~                              ~~~~~~~~~~~~~~~~~
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino: In function 'void tftScreen4()':
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:1208:11: error: unused variable 'co2diff' [-Werror=unused-variable]
     float co2diff = lastO2 - initialO2;
           ^~~~~~~
cc1plus.exe: some warnings being treated as errors

Are you getting the same result? any clue on what is wrong?

**Comment by kongmu511** [comment]
some T-display is diffrent, try the TFT_eSPI library in their GitHub repo, https://github.com/Xinyuan-LilyGO/TTGO-T-Display/tree/master/TFT_eSPI

**Comment by brunodom** [comment]
@kongmu511 thanks, but didn't work. I tried in the past and tried it again just to capture the error:

-----------
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
                         {icount++, "Done.", false, 0, 0}};
                                                         ^
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:985:57: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino: In function 'void doMenu()':
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:1020:18: error: variable 'sel' set but not used [-Werror=unused-but-set-variable]
             bool sel;
                  ^~~
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:1048:23: error: format '%d' expects argument of type 'int', but argument 5 has type 'void (*)()' [-Werror=format=]
         Serial.printf("cur %d, %d, %d", cur, menuitems[cur].toggle, menuitems[cur].fn);
                       ^~~~~~~~~~~~~~~~                              ~~~~~~~~~~~~~~~~~
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino: In function 'void tftScreen4()':
C:\Users\bruno\OneDrive\Projects\Training Insights\VO2Max\VO2Max-alternative\VO2max-main\VO2max\VO2max.ino:1208:11: error: unused variable 'co2diff' [-Werror=unused-variable]
     float co2diff = lastO2 - initialO2;
           ^~~~~~~
cc1plus.exe: some warnings being treated as errors
Multiple libraries were found for "TFT_eSPI.h"
  Used: C:\Users\bruno\OneDrive\Documents\Arduino\libraries\TFT_eSPI
  Not used: C:\Users\bruno\OneDrive\Documents\Arduino\libraries\TFT_eSPI_OLD

---------

As you can see, I renamed the folder to _OLD and copied from the TFT_eSPI from the git repository, it used the correct one but with the same outcome. :(

Do you have it working? can you share the file and the libraries (or at least the version) to make sure that is not a problem on my side.

**Comment by kongmu511** [comment]
we usally compile and program using Arduino 1.8.5

**Comment by brunodom** [comment]
> we usally compile and program using Arduino 1.8.5

Just tried with Arduino IDE 1.8.9 and same result:

C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::init()':
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:56:42: error: 'I2C_ERROR_OK' was not declared in this scope
   return (_i2cPort->endTransmission() == I2C_ERROR_OK);
                                          ^~~~~~~~~~~~
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::isConnected()':
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:61:43: error: 'I2C_ERROR_OK' was not declared in this scope
     return _i2cPort->endTransmission() == I2C_ERROR_OK;
                                           ^~~~~~~~~~~~
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::executeMcuMode()':
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:75:42: error: 'I2C_ERROR_OK' was not declared in this scope
   return (_i2cPort->endTransmission() == I2C_ERROR_OK);
                                          ^~~~~~~~~~~~
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'float Omron_D6FPH::getPressure()':
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:86:44: error: 'I2C_ERROR_OK' was not declared in this scope
         if (_i2cPort->endTransmission() == I2C_ERROR_OK){
                                            ^~~~~~~~~~~~
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'float Omron_D6FPH::getTemperature()':
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:104:44: error: 'I2C_ERROR_OK' was not declared in this scope
         if (_i2cPort->endTransmission() == I2C_ERROR_OK){
                                            ^~~~~~~~~~~~
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp: In member function 'boolean Omron_D6FPH::readRegister(uint8_t, uint16_t*)':
C:\Users\bruno\OneDrive\Documents\Arduino\libraries\Omron_D6F-PH_Arduino_Library\src\Omron_D6FPH.cpp:118:39: error: 'I2C_ERROR_OK' was not declared in this scope
     if(_i2cPort->endTransmission() == I2C_ERROR_OK){
                                       ^~~~~~~~~~~~

It is interesting that even with the Omron_D6F-PH example I got the same error.

**Comment by ihewitt** [comment]
I assume this is cleared now? The earlier errors appear to be the compiler is set to warnings on and warnings as errors, and looks like the original code isn't warning clear.
Changing the ide/compile settings to not fail on warnings should clear that until they are fixed in that code.
Clearly the second error if the omron example is failing, looks like there must be missing base dependencies somehow.
