### ISSUE TITLE
doubt about co2 hole

### ISSUE THREAD

**Issue by IOSUT** [ihewitt/VO2max#4]
Thanks for your contribution, I´m trying to upgrade the first version heloig with Venturi´s CO2 update, and my doubt is: 

need I  to fill the cover of Co2 with glue to not enable to pass O2 trought them to exterior? I´m assuming with this that the co2 hole maybe will affect to Bernoulli formule, V and pressure, but maybe the code incliudes it? 

Sorry for my ignorance, thanks.

**Comment by ihewitt** [comment]
Firstly, at the moment it's probably not worth making the co2 modification until we can find/decide a suitable co2 sensor. the SCD30 maxes out at 4% which is hit easily during exercise, so doesn't really provide much useful information.
But if you are adding one, do you have the additional small case to mount externally? If so then the only thing I used was a small filter (cut from a facemask) to cover the hole externally underneath the co2 sensor and case.

**Comment by IOSUT** [comment]
Thanks, I have the cover yes, I´m thinking maybe to use the Co2 values to estimate Fatmax, using lower values to limit of 4% of measurement that you said. 

Thanks!
